version: "2"

run:
  timeout: 5m

linters:
  enable:
    - errcheck
    - govet
    - staticcheck
    - unused
    - ineffassign
    - gocritic
    - revive

  settings:
    gocritic:
      enabled-tags:
        - diagnostic
        - style

issues:
  exclude-use-default: false
  max-issues-per-linter: 5
  max-same-issues: 0