package cli

import (
	"bufio"
	"errors"
	"fmt"
	"io"
	"os"
	"strings"

	"github.com/spf13/cobra"
)

// providerPreset holds defaults for a known LLM provider
type providerPreset struct {
	Name      string
	BaseURL   string
	APIKeyEnv string
	Model     string
}

// initConfig holds the values collected during interactive setup.
type initConfig struct {
	BaseURL   string
	APIKeyEnv string
	Model     string
	DocPaths  []string
}

var presets = []providerPreset{
	{
		Name:      "Gemini",
		BaseURL:   "https://generativelanguage.googleapis.com/v1beta/openai",
		APIKeyEnv: "GEMINI_API_KEY",
		Model:     "gemini-2.5-flash",
	},
	{
		Name:      "OpenAI",
		BaseURL:   "https://api.openai.com/v1",
		APIKeyEnv: "OPENAI_API_KEY",
		Model:     "gpt-4o",
	},
}

// ask prints a question and reads one line from the scanner.
func ask(sc *bufio.Scanner, w io.Writer, question, fallback string) (string, error) {
	if fallback != "" {
		if _, err := fmt.Fprintf(w, "%s [%s]: ", question, fallback); err != nil {
			return "", fmt.Errorf("writing prompt: %w", err)
		}
	} else {
		if _, err := fmt.Fprintf(w, "%s: ", question); err != nil {
			return "", fmt.Errorf("writing prompt: %w", err)
		}
	}
	if !sc.Scan() {
		return fallback, nil // EOF or error - use default
	}
	ans := strings.TrimSpace(sc.Text())
	if ans == "" {
		return fallback, nil
	}
	return ans, nil
}

// promptProvider asks the user to choose a provider and returns config values.
func promptProvider(sc *bufio.Scanner, w io.Writer) (initConfig, error) {
	if _, err := fmt.Fprintln(w, "\nLLM provider:"); err != nil {
		return initConfig{}, fmt.Errorf("writing provider header: %w", err)
	}
	for i, p := range presets {
		if _, err := fmt.Fprintf(w, "  [%d] %s\n", i+1, p.Name); err != nil {
			return initConfig{}, fmt.Errorf("writing preset: %w", err)
		}
	}
	if _, err := fmt.Fprintf(w, "  [%d] Custom\n", len(presets)+1); err != nil {
		return initConfig{}, fmt.Errorf("writing custom option: %w", err)
	}

	choice, err := ask(sc, w, "Choose", "1")
	if err != nil {
		return initConfig{}, err
	}

	idx := 0
	if _, err := fmt.Sscanf(choice, "%d", &idx); err == nil && idx >= 1 && idx <= len(presets) {
		p := presets[idx-1]
		model, err := ask(sc, w, "Model", p.Model)
		if err != nil {
			return initConfig{}, err
		}
		return initConfig{
			BaseURL:   p.BaseURL,
			APIKeyEnv: p.APIKeyEnv,
			Model:     model,
		}, nil
	}

	// Custom - ask for everything
	baseURL, err := ask(sc, w, "Base URL (OpenAI-compatible)", "")
	if err != nil {
		return initConfig{}, err
	}
	apiKeyEnv, err := ask(sc, w, "Env var holding API key", "")
	if err != nil {
		return initConfig{}, err
	}
	model, err := ask(sc, w, "Model name", "")
	if err != nil {
		return initConfig{}, err
	}
	return initConfig{
		BaseURL:   baseURL,
		APIKeyEnv: apiKeyEnv,
		Model:     model,
	}, nil
}

// writeConfig writes a .markguard.yaml with inline comments.
func writeConfig(path string, cfg initConfig) error {
	var pathLines string
	for _, p := range cfg.DocPaths {
		pathLines += fmt.Sprintf("    - %q\n", p)
	}

	content := fmt.Sprintf(`# mark-guard configuration - generated by "mark-guard init"

llm:
  # OpenAI-compatible endpoint.
  base_url: %q
  # Name of the env var that holds your API key (the key itself is never stored here).
  api_key_env: %q
  # Model name as accepted by the provider.
  model: %q

docs:
  # Directories and files mark-guard will scan for markdown docs.
  paths:
%s`, cfg.BaseURL, cfg.APIKeyEnv, cfg.Model, pathLines)

	return os.WriteFile(path, []byte(content), 0o644)
}

// promptDocPaths asks for comma-separated doc paths.
func promptDocPaths(sc *bufio.Scanner, w io.Writer) ([]string, error) {
	raw, err := ask(sc, w, "Doc paths (comma-separated)", "docs/, README.md")
	if err != nil {
		return nil, err
	}
	var paths []string
	for _, p := range strings.Split(raw, ",") {
		p = strings.TrimSpace(p)
		if p != "" {
			paths = append(paths, p)
		}
	}
	if len(paths) == 0 {
		paths = []string{"README.md"}
	}
	return paths, nil
}

// confirmOverwrite checks whether it is safe to write to path.
func confirmOverwrite(sc *bufio.Scanner, w io.Writer, path string) (bool, error) {
	_, err := os.Stat(path)
	if err != nil {
		if errors.Is(err, os.ErrNotExist) {
			return true, nil // file doesn't exist, safe to write
		}
		// Permission denied, broken symlink, etc.
		return false, fmt.Errorf("checking %s: %w", path, err)
	}
	// File exists - ask user
	if _, err := fmt.Fprintf(w, "%s already exists.\n", path); err != nil {
		return false, fmt.Errorf("writing overwrite warning: %w", err)
	}
	ans, err := ask(sc, w, "Overwrite?", "n")
	if err != nil {
		return false, err
	}
	return strings.EqualFold(ans, "y") || strings.EqualFold(ans, "yes"), nil
}

// runConfigInit drives the interactive config generation.
func runConfigInit(configPath string, in io.Reader, out io.Writer) error {
	sc := bufio.NewScanner(in)

	// Overwrite guard
	proceed, err := confirmOverwrite(sc, out, configPath)
	if err != nil {
		return err
	}
	if !proceed {
		if _, err := fmt.Fprintln(out, "aborted"); err != nil {
			return fmt.Errorf("writing abort message: %w", err)
		}
		return nil
	}

	// Collect config from user
	cfg, err := promptProvider(sc, out)
	if err != nil {
		return err
	}
	cfg.DocPaths, err = promptDocPaths(sc, out)
	if err != nil {
		return err
	}

	if err := writeConfig(configPath, cfg); err != nil {
		return fmt.Errorf("writing config: %w", err)
	}
	if _, err := fmt.Fprintf(out, "\n✓ wrote %s\n", configPath); err != nil {
		return fmt.Errorf("writing success message: %w", err)
	}
	return nil
}

func newInitCmd() *cobra.Command {
	var configPath string
	cmd := &cobra.Command{
		Use:   "init",
		Short: "Generate a .markguard.yaml config file",
		RunE: func(_ *cobra.Command, _ []string) error {
			return runConfigInit(configPath, os.Stdin, os.Stdout)
		},
	}
	cmd.Flags().StringVar(&configPath, "config", ".markguard.yaml", "output path")
	return cmd
}
